//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.proxy.xsd._3.Boolean;
import gov.niem.release.niem.structures._3.AugmentationType;


/**
 * A data type that supplements nc:IncidentType.
 * 
 * <p>Java class for IncidentAugmentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentAugmentationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}AugmentationType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fbi.gov/cjis/1.0}IncidentReportDateIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}OffenseCargoTheftIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentAugmentationType", propOrder = {
    "incidentReportDateIndicator",
    "offenseCargoTheftIndicator"
})
public class IncidentAugmentationType
    extends AugmentationType
{

    @XmlElement(name = "IncidentReportDateIndicator", nillable = true)
    protected Boolean incidentReportDateIndicator;
    @XmlElement(name = "OffenseCargoTheftIndicator", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/")
    protected Boolean offenseCargoTheftIndicator;

    /**
     * Gets the value of the incidentReportDateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIncidentReportDateIndicator() {
        return incidentReportDateIndicator;
    }

    /**
     * Sets the value of the incidentReportDateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncidentReportDateIndicator(Boolean value) {
        this.incidentReportDateIndicator = value;
    }

    /**
     * Gets the value of the offenseCargoTheftIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getOffenseCargoTheftIndicator() {
        return offenseCargoTheftIndicator;
    }

    /**
     * Sets the value of the offenseCargoTheftIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOffenseCargoTheftIndicator(Boolean value) {
        this.offenseCargoTheftIndicator = value;
    }

}
