//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.codes.fbi_ucr._3.ArresteeWeaponCodeType;
import gov.niem.release.niem.structures._3.AugmentationType;


/**
 * Augmentation for j:SubjectAugmenationPoint
 * 
 * <p>Java class for SubjectAugmentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectAugmentationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}AugmentationType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}SubjectArmedWith"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectAugmentationType", propOrder = {
    "subjectArmedWith"
})
public class SubjectAugmentationType
    extends AugmentationType
{

    @XmlElementRef(name = "SubjectArmedWith", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/", type = JAXBElement.class)
    protected JAXBElement<?> subjectArmedWith;

    /**
     * Gets the value of the subjectArmedWith property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArresteeWeaponCodeType }{@code >}
     *     
     */
    public JAXBElement<?> getSubjectArmedWith() {
        return subjectArmedWith;
    }

    /**
     * Sets the value of the subjectArmedWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArresteeWeaponCodeType }{@code >}
     *     
     */
    public void setSubjectArmedWith(JAXBElement<?> value) {
        this.subjectArmedWith = value;
    }

}
