//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.niem.release.niem.domains.jxdm._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.codes.fbi_ucr._3.ArrestCategoryCodeType;
import gov.niem.release.niem.niem_core._3.ActivityType;


/**
 * A data type for the apprehension of a subject by a peace official.
 * 
 * <p>Java class for ArrestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/niem-core/3.0/}ActivityType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArrestCharge" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArrestCategory" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrestType", propOrder = {
    "arrestCharge",
    "arrestCategory"
})
public class ArrestType
    extends ActivityType
{

    @XmlElement(name = "ArrestCharge")
    protected ChargeType arrestCharge;
    @XmlElementRef(name = "ArrestCategory", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/", type = JAXBElement.class, required = false)
    protected JAXBElement<?> arrestCategory;

    /**
     * Gets the value of the arrestCharge property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeType }
     *     
     */
    public ChargeType getArrestCharge() {
        return arrestCharge;
    }

    /**
     * Sets the value of the arrestCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeType }
     *     
     */
    public void setArrestCharge(ChargeType value) {
        this.arrestCharge = value;
    }

    /**
     * Gets the value of the arrestCategory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrestCategoryCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getArrestCategory() {
        return arrestCategory;
    }

    /**
     * Sets the value of the arrestCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrestCategoryCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setArrestCategory(JAXBElement<?> value) {
        this.arrestCategory = value;
    }

}
