//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.niem.release.niem.domains.jxdm._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.release.niem.codes.fbi_ndex._3.JuvenileDispositionCodeType;
import gov.niem.release.niem.codes.fbi_ucr._3.ArresteeWeaponCodeType;
import gov.niem.release.niem.codes.fbi_ucr._3.MultipleArresteeSegmentsCodeType;
import gov.niem.release.niem.proxy.xsd._3.Boolean;
import gov.niem.release.niem.proxy.xsd._3.String;


/**
 * A data type for a person who is arrested for a violation of a criminal statute, ordinance or rule.
 * 
 * <p>Java class for ArresteeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArresteeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/domains/jxdm/5.2/}SubjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArrestSequenceID" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArresteeClearanceIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArresteeArmedWith" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArresteeJuvenileDisposition" minOccurs="0"/>
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/5.2/}ArrestSubjectCount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArresteeType", propOrder = {
    "arrestSequenceID",
    "arresteeClearanceIndicator",
    "arresteeArmedWith",
    "arresteeJuvenileDisposition",
    "arrestSubjectCount"
})
public class ArresteeType
    extends SubjectType
{

    @XmlElement(name = "ArrestSequenceID")
    protected String arrestSequenceID;
    @XmlElement(name = "ArresteeClearanceIndicator")
    protected Boolean arresteeClearanceIndicator;
    @XmlElementRef(name = "ArresteeArmedWith", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> arresteeArmedWith;
    @XmlElementRef(name = "ArresteeJuvenileDisposition", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/", type = JAXBElement.class, required = false)
    protected JAXBElement<?> arresteeJuvenileDisposition;
    @XmlElementRef(name = "ArrestSubjectCount", namespace = "http://release.niem.gov/niem/domains/jxdm/5.2/", type = JAXBElement.class, required = false)
    protected JAXBElement<?> arrestSubjectCount;

    /**
     * Gets the value of the arrestSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrestSequenceID() {
        return arrestSequenceID;
    }

    /**
     * Sets the value of the arrestSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrestSequenceID(String value) {
        this.arrestSequenceID = value;
    }

    /**
     * Gets the value of the arresteeClearanceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getArresteeClearanceIndicator() {
        return arresteeClearanceIndicator;
    }

    /**
     * Sets the value of the arresteeClearanceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setArresteeClearanceIndicator(Boolean value) {
        this.arresteeClearanceIndicator = value;
    }

    /**
     * Gets the value of the arresteeArmedWith property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arresteeArmedWith property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArresteeArmedWith().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ArresteeWeaponCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getArresteeArmedWith() {
        if (arresteeArmedWith == null) {
            arresteeArmedWith = new ArrayList<JAXBElement<?>>();
        }
        return this.arresteeArmedWith;
    }

    /**
     * Gets the value of the arresteeJuvenileDisposition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link JuvenileDispositionCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getArresteeJuvenileDisposition() {
        return arresteeJuvenileDisposition;
    }

    /**
     * Sets the value of the arresteeJuvenileDisposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link JuvenileDispositionCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setArresteeJuvenileDisposition(JAXBElement<?> value) {
        this.arresteeJuvenileDisposition = value;
    }

    /**
     * Gets the value of the arrestSubjectCount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MultipleArresteeSegmentsCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getArrestSubjectCount() {
        return arrestSubjectCount;
    }

    /**
     * Sets the value of the arrestSubjectCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MultipleArresteeSegmentsCodeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setArrestSubjectCount(JAXBElement<?> value) {
        this.arrestSubjectCount = value;
    }

}
