//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.niem.release.niem.codes.fbi_ndex._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriminalActivityCategoryNDExCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CriminalActivityCategoryNDExCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Assisting"/>
 *     &lt;enumeration value="Buying"/>
 *     &lt;enumeration value="Buying_Receiving"/>
 *     &lt;enumeration value="Concealing"/>
 *     &lt;enumeration value="Consuming"/>
 *     &lt;enumeration value="Cultivating"/>
 *     &lt;enumeration value="Cultivating_Manufacturing_Publishing"/>
 *     &lt;enumeration value="Distributing"/>
 *     &lt;enumeration value="Distributing_Selling"/>
 *     &lt;enumeration value="Exploiting Children"/>
 *     &lt;enumeration value="Importing"/>
 *     &lt;enumeration value="Manufacturing"/>
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Operating"/>
 *     &lt;enumeration value="Operating_Promoting_Assisting"/>
 *     &lt;enumeration value="Possessing"/>
 *     &lt;enumeration value="Possessing_Concealing"/>
 *     &lt;enumeration value="Promoting"/>
 *     &lt;enumeration value="Publishing"/>
 *     &lt;enumeration value="Receiving"/>
 *     &lt;enumeration value="Selling"/>
 *     &lt;enumeration value="Transmitting"/>
 *     &lt;enumeration value="Transporting"/>
 *     &lt;enumeration value="Transporting_Transmitting_Importing"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Using"/>
 *     &lt;enumeration value="Using_Consuming"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CriminalActivityCategoryNDExCodeSimpleType")
@XmlEnum
public enum CriminalActivityCategoryNDExCodeSimpleType {


    /**
     * Assisting
     * 
     */
    @XmlEnumValue("Assisting")
    ASSISTING("Assisting"),

    /**
     * Buying
     * 
     */
    @XmlEnumValue("Buying")
    BUYING("Buying"),

    /**
     * Buying_Receiving
     * 
     */
    @XmlEnumValue("Buying_Receiving")
    BUYING_RECEIVING("Buying_Receiving"),

    /**
     * Concealing
     * 
     */
    @XmlEnumValue("Concealing")
    CONCEALING("Concealing"),

    /**
     * Consuming
     * 
     */
    @XmlEnumValue("Consuming")
    CONSUMING("Consuming"),

    /**
     * Cultivating
     * 
     */
    @XmlEnumValue("Cultivating")
    CULTIVATING("Cultivating"),

    /**
     * Cultivating_Manufacturing_Publishing
     * 
     */
    @XmlEnumValue("Cultivating_Manufacturing_Publishing")
    CULTIVATING_MANUFACTURING_PUBLISHING("Cultivating_Manufacturing_Publishing"),

    /**
     * Distributing
     * 
     */
    @XmlEnumValue("Distributing")
    DISTRIBUTING("Distributing"),

    /**
     * Distributing_Selling
     * 
     */
    @XmlEnumValue("Distributing_Selling")
    DISTRIBUTING_SELLING("Distributing_Selling"),

    /**
     * Exploiting Children
     * 
     */
    @XmlEnumValue("Exploiting Children")
    EXPLOITING_CHILDREN("Exploiting Children"),

    /**
     * Importing
     * 
     */
    @XmlEnumValue("Importing")
    IMPORTING("Importing"),

    /**
     * Manufacturing
     * 
     */
    @XmlEnumValue("Manufacturing")
    MANUFACTURING("Manufacturing"),

    /**
     * None
     * 
     */
    @XmlEnumValue("None")
    NONE("None"),

    /**
     * Operating
     * 
     */
    @XmlEnumValue("Operating")
    OPERATING("Operating"),

    /**
     * Operating_Promoting_Assisting
     * 
     */
    @XmlEnumValue("Operating_Promoting_Assisting")
    OPERATING_PROMOTING_ASSISTING("Operating_Promoting_Assisting"),

    /**
     * Possessing
     * 
     */
    @XmlEnumValue("Possessing")
    POSSESSING("Possessing"),

    /**
     * Possessing_Concealing
     * 
     */
    @XmlEnumValue("Possessing_Concealing")
    POSSESSING_CONCEALING("Possessing_Concealing"),

    /**
     * Promoting
     * 
     */
    @XmlEnumValue("Promoting")
    PROMOTING("Promoting"),

    /**
     * Publishing
     * 
     */
    @XmlEnumValue("Publishing")
    PUBLISHING("Publishing"),

    /**
     * Receiving
     * 
     */
    @XmlEnumValue("Receiving")
    RECEIVING("Receiving"),

    /**
     * Selling
     * 
     */
    @XmlEnumValue("Selling")
    SELLING("Selling"),

    /**
     * Transmitting
     * 
     */
    @XmlEnumValue("Transmitting")
    TRANSMITTING("Transmitting"),

    /**
     * Transporting
     * 
     */
    @XmlEnumValue("Transporting")
    TRANSPORTING("Transporting"),

    /**
     * Transporting_Transmitting_Importing
     * 
     */
    @XmlEnumValue("Transporting_Transmitting_Importing")
    TRANSPORTING_TRANSMITTING_IMPORTING("Transporting_Transmitting_Importing"),

    /**
     * Unknown
     * 
     */
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),

    /**
     * Using
     * 
     */
    @XmlEnumValue("Using")
    USING("Using"),

    /**
     * Using_Consuming
     * 
     */
    @XmlEnumValue("Using_Consuming")
    USING_CONSUMING("Using_Consuming");
    private final String value;

    CriminalActivityCategoryNDExCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CriminalActivityCategoryNDExCodeSimpleType fromValue(String v) {
        for (CriminalActivityCategoryNDExCodeSimpleType c: CriminalActivityCategoryNDExCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
