//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.niem.release.niem.codes.fbi_ndex._3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niem.release.niem.codes.fbi_ndex._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niem.release.niem.codes.fbi_ndex._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JuvenileDispositionCodeType }
     * 
     */
    public JuvenileDispositionCodeType createJuvenileDispositionCodeType() {
        return new JuvenileDispositionCodeType();
    }

    /**
     * Create an instance of {@link RACCodeType }
     * 
     */
    public RACCodeType createRACCodeType() {
        return new RACCodeType();
    }

    /**
     * Create an instance of {@link IncidentStatusCodeType }
     * 
     */
    public IncidentStatusCodeType createIncidentStatusCodeType() {
        return new IncidentStatusCodeType();
    }

    /**
     * Create an instance of {@link BiasMotivationCodeType }
     * 
     */
    public BiasMotivationCodeType createBiasMotivationCodeType() {
        return new BiasMotivationCodeType();
    }

    /**
     * Create an instance of {@link CriminalActivityCategoryNDExCodeType }
     * 
     */
    public CriminalActivityCategoryNDExCodeType createCriminalActivityCategoryNDExCodeType() {
        return new CriminalActivityCategoryNDExCodeType();
    }

}
