//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://release.niem.gov/niem/codes/fbi_ndex/3.1/")
package gov.niem.release.niem.codes.fbi_ndex._3;
