//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis.cjis_codes._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemStatusCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemStatusCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="BAIT"/>
 *     &lt;enumeration value="BURNED"/>
 *     &lt;enumeration value="CARGO"/>
 *     &lt;enumeration value="CONTRABAND"/>
 *     &lt;enumeration value="COUNTERFEITED"/>
 *     &lt;enumeration value="CULTIVATED"/>
 *     &lt;enumeration value="DAMAGED"/>
 *     &lt;enumeration value="DESTROYED"/>
 *     &lt;enumeration value="DESTROYED_DAMAGED_VANDALIZED"/>
 *     &lt;enumeration value="FOUND"/>
 *     &lt;enumeration value="LOST"/>
 *     &lt;enumeration value="RECOVERED"/>
 *     &lt;enumeration value="RETURNED"/>
 *     &lt;enumeration value="SEIZED"/>
 *     &lt;enumeration value="STOLEN"/>
 *     &lt;enumeration value="STOLEN_BRIBED"/>
 *     &lt;enumeration value="STOLEN_DEFRAUDED"/>
 *     &lt;enumeration value="STOLEN_EMBEZZLED"/>
 *     &lt;enumeration value="STOLEN_EXTORTED"/>
 *     &lt;enumeration value="STOLEN_RANSOMED"/>
 *     &lt;enumeration value="STOLEN_ROBBED"/>
 *     &lt;enumeration value="VANDALIZED"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ItemStatusCodeSimpleType")
@XmlEnum
public enum ItemStatusCodeSimpleType {


    /**
     * Bait
     * 
     */
    BAIT,

    /**
     * Burned
     * 
     */
    BURNED,

    /**
     * Cargo
     * 
     */
    CARGO,

    /**
     * Contraband
     * 
     */
    CONTRABAND,

    /**
     * Counterfeited, includes forged
     * 
     */
    COUNTERFEITED,

    /**
     * Cultivated
     * 
     */
    CULTIVATED,

    /**
     * Damaged
     * 
     */
    DAMAGED,

    /**
     * Destroyed
     * 
     */
    DESTROYED,

    /**
     * Destroyed_Damaged_Vandalized
     * 
     */
    DESTROYED_DAMAGED_VANDALIZED,

    /**
     * Found
     * 
     */
    FOUND,

    /**
     * Lost
     * 
     */
    LOST,

    /**
     * Recovered  (To impound property previously stolen)
     * 
     */
    RECOVERED,

    /**
     * Returned
     * 
     */
    RETURNED,

    /**
     * Seized (To impound property not previously stolen)
     * 
     */
    SEIZED,

    /**
     * Stolen
     * 
     */
    STOLEN,

    /**
     * Stolen_Bribed
     * 
     */
    STOLEN_BRIBED,

    /**
     * Stolen_Defrauded
     * 
     */
    STOLEN_DEFRAUDED,

    /**
     * Stolen_Embezzled
     * 
     */
    STOLEN_EMBEZZLED,

    /**
     * Stolen_Extorted
     * 
     */
    STOLEN_EXTORTED,

    /**
     * Stolen_Ransomed
     * 
     */
    STOLEN_RANSOMED,

    /**
     * Stolen_Robbed
     * 
     */
    STOLEN_ROBBED,

    /**
     * Vandalized
     * 
     */
    VANDALIZED,

    /**
     * None
     * 
     */
    NONE,

    /**
     * Unknown
     * 
     */
    UNKNOWN;

    public String value() {
        return name();
    }

    public static ItemStatusCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
