//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis.nibrs._4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.fbi.cjis.nibrs.nibrs_codes._4.NIBRSReportCategoryCodeType;
import gov.fbi.cjis.nibrs.nibrs_codes._4.ReportActionCategoryCodeType;
import gov.niem.release.niem.niem_core._3.DateType;
import gov.niem.release.niem.niem_core._3.OrganizationType;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * A data type for header information for the report.
 * 
 * <p>Java class for ReportHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportHeaderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fbi.gov/cjis/nibrs/4.2}NIBRSReportCategoryCode"/>
 *         &lt;element ref="{http://fbi.gov/cjis/nibrs/4.2}ReportActionCategoryCode"/>
 *         &lt;element ref="{http://fbi.gov/cjis/nibrs/4.2}ReportDate"/>
 *         &lt;element ref="{http://fbi.gov/cjis/nibrs/4.2}ReportingAgency"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportHeaderType", propOrder = {
    "nibrsReportCategoryCode",
    "reportActionCategoryCode",
    "reportDate",
    "reportingAgency"
})
public class ReportHeaderType
    extends ObjectType
{

    @XmlElement(name = "NIBRSReportCategoryCode", required = true, nillable = true)
    protected NIBRSReportCategoryCodeType nibrsReportCategoryCode;
    @XmlElement(name = "ReportActionCategoryCode", required = true, nillable = true)
    protected ReportActionCategoryCodeType reportActionCategoryCode;
    @XmlElement(name = "ReportDate", required = true)
    protected DateType reportDate;
    @XmlElement(name = "ReportingAgency", required = true)
    protected OrganizationType reportingAgency;

    /**
     * Gets the value of the nibrsReportCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link NIBRSReportCategoryCodeType }
     *     
     */
    public NIBRSReportCategoryCodeType getNIBRSReportCategoryCode() {
        return nibrsReportCategoryCode;
    }

    /**
     * Sets the value of the nibrsReportCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NIBRSReportCategoryCodeType }
     *     
     */
    public void setNIBRSReportCategoryCode(NIBRSReportCategoryCodeType value) {
        this.nibrsReportCategoryCode = value;
    }

    /**
     * Gets the value of the reportActionCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReportActionCategoryCodeType }
     *     
     */
    public ReportActionCategoryCodeType getReportActionCategoryCode() {
        return reportActionCategoryCode;
    }

    /**
     * Sets the value of the reportActionCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportActionCategoryCodeType }
     *     
     */
    public void setReportActionCategoryCode(ReportActionCategoryCodeType value) {
        this.reportActionCategoryCode = value;
    }

    /**
     * Gets the value of the reportDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getReportDate() {
        return reportDate;
    }

    /**
     * Sets the value of the reportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setReportDate(DateType value) {
        this.reportDate = value;
    }

    /**
     * Gets the value of the reportingAgency property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getReportingAgency() {
        return reportingAgency;
    }

    /**
     * Sets the value of the reportingAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setReportingAgency(OrganizationType value) {
        this.reportingAgency = value;
    }

}
