//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis.nibrs._4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.fbi.cjis._1.MessageMetadataType;
import gov.niem.release.niem.structures._3.ObjectType;


/**
 * The root element for a NIBRS exchange
 * 
 * <p>Java class for SubmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmissionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://release.niem.gov/niem/structures/3.0/}ObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fbi.gov/cjis/1.0}MessageMetadata"/>
 *         &lt;element ref="{http://fbi.gov/cjis/nibrs/4.2}Report"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionType", propOrder = {
    "messageMetadata",
    "report"
})
public class SubmissionType
    extends ObjectType
{

    @XmlElement(name = "MessageMetadata", namespace = "http://fbi.gov/cjis/1.0", required = true)
    protected MessageMetadataType messageMetadata;
    @XmlElement(name = "Report", required = true)
    protected ReportType report;

    /**
     * Gets the value of the messageMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link MessageMetadataType }
     *     
     */
    public MessageMetadataType getMessageMetadata() {
        return messageMetadata;
    }

    /**
     * Sets the value of the messageMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageMetadataType }
     *     
     */
    public void setMessageMetadata(MessageMetadataType value) {
        this.messageMetadata = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link ReportType }
     *     
     */
    public ReportType getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportType }
     *     
     */
    public void setReport(ReportType value) {
        this.report = value;
    }

}
