//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis.nibrs.nibrs_codes._4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriminalActivityCategoryCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CriminalActivityCategoryCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="U"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CriminalActivityCategoryCodeSimpleType")
@XmlEnum
public enum CriminalActivityCategoryCodeSimpleType {


    /**
     * Simple/Gross Neglect
     * 
     */
    A,

    /**
     * Buying/Receiving
     * 
     */
    B,

    /**
     * Cultivating/Manufacturing/Publishing (i.e., production of any type)
     * 
     */
    C,

    /**
     * Distributing/Selling
     * 
     */
    D,

    /**
     * Exploiting Children
     * 
     */
    E,

    /**
     * Organized Abuse (Dog Fighting and Cock Fighting)
     * 
     */
    F,

    /**
     * Other Gang
     * 
     */
    G,

    /**
     * Intentional Abuse and Torture (tormenting, mutilating, maiming,poisoning, or abandonment)
     * 
     */
    I,

    /**
     * Juvenile Gang
     * 
     */
    J,

    /**
     * None/Unknown
     * 
     */
    N,

    /**
     * Operating/Promoting/Assisting
     * 
     */
    O,

    /**
     * Possessing/Concealing
     * 
     */
    P,

    /**
     * Animal Sexual Abuse (Bestiality)
     * 
     */
    S,

    /**
     * Transporting/Transmitting/Importing
     * 
     */
    T,

    /**
     * Using/Consuming
     * 
     */
    U;

    public String value() {
        return name();
    }

    public static CriminalActivityCategoryCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
