//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.fbi.cjis.nibrs.nibrs_codes._4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NIBRSReportCategoryCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NIBRSReportCategoryCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="GROUP A INCIDENT REPORT"/>
 *     &lt;enumeration value="GROUP B ARREST REPORT"/>
 *     &lt;enumeration value="ZERO REPORT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NIBRSReportCategoryCodeSimpleType")
@XmlEnum
public enum NIBRSReportCategoryCodeSimpleType {


    /**
     * Group A Incident Report
     * 
     */
    @XmlEnumValue("GROUP A INCIDENT REPORT")
    GROUP_A_INCIDENT_REPORT("GROUP A INCIDENT REPORT"),

    /**
     * Group B Arrest Report
     * 
     */
    @XmlEnumValue("GROUP B ARREST REPORT")
    GROUP_B_ARREST_REPORT("GROUP B ARREST REPORT"),

    /**
     * Zero Report
     * 
     */
    @XmlEnumValue("ZERO REPORT")
    ZERO_REPORT("ZERO REPORT");
    private final String value;

    NIBRSReportCategoryCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NIBRSReportCategoryCodeSimpleType fromValue(String v) {
        for (NIBRSReportCategoryCodeSimpleType c: NIBRSReportCategoryCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
