//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 10:29:14 AM EST 
//


package gov.niem.release.niem.codes.fbi_ucr._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrugCategoryCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DrugCategoryCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="X"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DrugCategoryCodeSimpleType")
@XmlEnum
public enum DrugCategoryCodeSimpleType {


    /**
     * crack cocaine
     * 
     */
    A,

    /**
     * cocaine
     * 
     */
    B,

    /**
     * hashish
     * 
     */
    C,

    /**
     * heroin
     * 
     */
    D,

    /**
     * marijuana
     * 
     */
    E,

    /**
     * morphine
     * 
     */
    F,

    /**
     * opium
     * 
     */
    G,

    /**
     * other narcotics
     * 
     */
    H,

    /**
     * LSD
     * 
     */
    I,

    /**
     * PCP
     * 
     */
    J,

    /**
     * other hallucingens
     * 
     */
    K,

    /**
     * amphetamines/ methamphetamines
     * 
     */
    L,

    /**
     * other stimulants
     * 
     */
    M,

    /**
     * barbiturates
     * 
     */
    N,

    /**
     * other depressants
     * 
     */
    O,

    /**
     * other drugs
     * 
     */
    P,

    /**
     * unknown drug type
     * 
     */
    U,

    /**
     * over 3 drug types
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static DrugCategoryCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
